force-app/main/default/objects/CQ_Customisation_Setup__c/CQ_Customisation_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Setting will be Used for Enable the Integration for CQ</description>
    <label>CQ Customisation Setup</label>
</CustomObject>

force-app/main/default/objects/CQ_Customisation_Setup__c/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <label>Endpoint URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CQConfigurationRestServiceUtil.cls
public with sharing class CQConfigurationRestServiceUtil {
	public String CQ_REST_ENDPOINT;
    public String X_API_KEY;
	public Boolean isActive;
    public String CONTENT_TYPE = 'application/json';
    public String METHOD = 'GET';
    
    private static CQConfigurationRestServiceUtil instance;
    
    private CQConfigurationRestServiceUtil(){
        //Integration setup configuration details form Custom setting
        CQ_Customisation_Setup__c cqSetupRec = CQ_Customisation_Setup__c.getOrgDefaults();
        CQ_REST_ENDPOINT = cqSetupRec.Endpoint_URL__c;
        X_API_KEY = cqSetupRec.Api_Key__c;
        isActive = cqSetupRec.Active__c; 
    }
    
    public static CQConfigurationRestServiceUtil getInstance()
    {
        if (instance == null){
            instance = new CQConfigurationRestServiceUtil();
        }  
        return instance;
    }
}